/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDiscordReportRouteImport } from './routes/api.discord-report'
import { Route as ApiBootstrapAdminRouteImport } from './routes/api.bootstrap-admin'
import { Route as ApiPublicDiscordReportRouteImport } from './routes/api.public.discord-report'
import { Route as ApiPublicDiscordReportHealthRouteImport } from './routes/api.public.discord-report.health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordReportRoute = ApiDiscordReportRouteImport.update({
  id: '/api/discord-report',
  path: '/api/discord-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBootstrapAdminRoute = ApiBootstrapAdminRouteImport.update({
  id: '/api/bootstrap-admin',
  path: '/api/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordReportRoute = ApiPublicDiscordReportRouteImport.update({
  id: '/api/public/discord-report',
  path: '/api/public/discord-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordReportHealthRoute =
  ApiPublicDiscordReportHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => ApiPublicDiscordReportRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/bootstrap-admin': typeof ApiBootstrapAdminRoute
  '/api/discord-report': typeof ApiDiscordReportRoute
  '/api/public/discord-report': typeof ApiPublicDiscordReportRouteWithChildren
  '/api/public/discord-report/health': typeof ApiPublicDiscordReportHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/bootstrap-admin': typeof ApiBootstrapAdminRoute
  '/api/discord-report': typeof ApiDiscordReportRoute
  '/api/public/discord-report': typeof ApiPublicDiscordReportRouteWithChildren
  '/api/public/discord-report/health': typeof ApiPublicDiscordReportHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/bootstrap-admin': typeof ApiBootstrapAdminRoute
  '/api/discord-report': typeof ApiDiscordReportRoute
  '/api/public/discord-report': typeof ApiPublicDiscordReportRouteWithChildren
  '/api/public/discord-report/health': typeof ApiPublicDiscordReportHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/bootstrap-admin'
    | '/api/discord-report'
    | '/api/public/discord-report'
    | '/api/public/discord-report/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/bootstrap-admin'
    | '/api/discord-report'
    | '/api/public/discord-report'
    | '/api/public/discord-report/health'
  id:
    | '__root__'
    | '/'
    | '/api/bootstrap-admin'
    | '/api/discord-report'
    | '/api/public/discord-report'
    | '/api/public/discord-report/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBootstrapAdminRoute: typeof ApiBootstrapAdminRoute
  ApiDiscordReportRoute: typeof ApiDiscordReportRoute
  ApiPublicDiscordReportRoute: typeof ApiPublicDiscordReportRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord-report': {
      id: '/api/discord-report'
      path: '/api/discord-report'
      fullPath: '/api/discord-report'
      preLoaderRoute: typeof ApiDiscordReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bootstrap-admin': {
      id: '/api/bootstrap-admin'
      path: '/api/bootstrap-admin'
      fullPath: '/api/bootstrap-admin'
      preLoaderRoute: typeof ApiBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord-report': {
      id: '/api/public/discord-report'
      path: '/api/public/discord-report'
      fullPath: '/api/public/discord-report'
      preLoaderRoute: typeof ApiPublicDiscordReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord-report/health': {
      id: '/api/public/discord-report/health'
      path: '/health'
      fullPath: '/api/public/discord-report/health'
      preLoaderRoute: typeof ApiPublicDiscordReportHealthRouteImport
      parentRoute: typeof ApiPublicDiscordReportRoute
    }
  }
}

interface ApiPublicDiscordReportRouteChildren {
  ApiPublicDiscordReportHealthRoute: typeof ApiPublicDiscordReportHealthRoute
}

const ApiPublicDiscordReportRouteChildren: ApiPublicDiscordReportRouteChildren =
  {
    ApiPublicDiscordReportHealthRoute: ApiPublicDiscordReportHealthRoute,
  }

const ApiPublicDiscordReportRouteWithChildren =
  ApiPublicDiscordReportRoute._addFileChildren(
    ApiPublicDiscordReportRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBootstrapAdminRoute: ApiBootstrapAdminRoute,
  ApiDiscordReportRoute: ApiDiscordReportRoute,
  ApiPublicDiscordReportRoute: ApiPublicDiscordReportRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
